blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
	url(r'^$', views.post_list, name='post_list'),
	url(r'^inscriptions/$', views.inscr_list, name='inscr_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^user/(?P<pk>[0-9]+)/$', views.user_detail, name='user_detail'),
	url(r'^your_profile/$', views.profile_detail, name='profile_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^inscr/new/$', views.inscr_new, name='inscr_new'),
	url(r'^inscr/(?P<pk>[0-9]+)/$', views.inscr_detail, name='inscr_detail'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
	url(r'^login/$', auth_views.login, {'template_name': 'blog/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
	url(r'^admin/', admin.site.urls),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
	url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
	url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
	url(r'^post_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<pidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
	        views.post_confirm, name='post_confirm'),
	url(r'^place/new/$', views.place_new, name='place_new'),
	url(r'^places/$', views.place_list, name='place_list'),
	url(r'^place/(?P<pk>[0-9]+)/$', views.place_detail, name='place_detail'),
	url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
	url(r'', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.gis.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Inscription(models.Model):
    fn_parent = models.CharField(max_length=200)
    sn_parent = models.CharField(max_length=200)
    fn_child = models.CharField(max_length=200)
    sn_child = models.CharField(max_length=200)
    dob_child = models.DateField(null=True, blank=True)
    phone_parent = models.CharField(max_length=20, default='')
    bio_child = models.TextField(blank=True)
    first_choice = models.CharField(max_length=200)
    second_choice = models.CharField(max_length=200)
    published_date = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    def __str__(self):
        return '%s %s %s %s' % (self.published_date, self.fn_child, self.sn_child, self.dob_child)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    gruppo = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    birth_date = models.DateField(null=True, blank=True)
    registration_date = models.DateTimeField(blank=True, null=True)
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    nomeautore = models.CharField(max_length=500)
    gruppo = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    subtitle = models.TextField(max_length=500)
    text = models.TextField()
    approval = models.TextField()
    approved = models.BooleanField(default=True)
    img = models.ImageField(upload_to='post_img/', blank=True, null=True)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    last_login = models.DateTimeField(
            default=timezone.now)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return '%s %s %s %s' % (self.published_date, self.title, self.nomeautore, self.gruppo)
    def image_tag(self):
        return u'<img style=" max-width: 400px; width: 100%;" src="%s" />' % (self.img.url)
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True


class Place(models.Model):
    typ = models.CharField(max_length=200)
    where = models.CharField(max_length=200)
    coordinates = models.PointField()
    heat = models.CharField(max_length=200)
    capacity = models.IntegerField()
    cost = models.CharField(max_length=200)
    last_group = models.CharField(max_length=200)
    contacts = models.CharField(max_length=200)
    description = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    def publish(self):
        self.published_date = timezone.now()
        self.save()

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.utils import timezone
from .models import Post, Inscription, Place
from .forms import PostForm, SignUpForm, InscrForm, PlaceForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string, get_template 
from .tokens import account_activation_token, post_token
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .filters import InscriptionFilter, PlaceFilter
import datetime
from django.template import Context
from weasyprint import HTML, CSS
"""
POST ENVIRONMENT

"""

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required(login_url='/login/')
def post_new(request):
    post = None
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if (form.is_valid() and request.user.is_staff):
            post = form.save(commit=False)
            post.author = request.user
            post.nomeautore = request.user.first_name + ' ' + request.user.last_name
            post.gruppo = request.user.profile.gruppo
            post.approved = True
            post.published_date = timezone.now()
            post_x = form.cleaned_data.get('x')
            post.save()
            if post.img:
                form.save_img()
            return redirect('post_detail', pk=post.pk)
        elif form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.nomeautore = request.user.first_name + ' ' + request.user.last_name
            post.gruppo = request.user.profile.gruppo
            post.approved = False
            post.save()
            if post.img:
                form.save_img()
            target = User.objects.filter(profile__gruppo=post.gruppo, is_staff=True)
            if not target:
                target = User.objects.filter(is_staff=True)
            for user in target:
                current_site = get_current_site(request)
                subject = 'Richiesta post'
                if post.img:
                    message = render_to_string('blog/post_request_email.html', {
                        'user': request.user,
                        'domain': current_site.domain,
                        'title': post.title,
                        'subtitle': post.subtitle,
                        'text': post.text,
                        'image': post.img.url,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'pid': urlsafe_base64_encode(force_bytes(post.pk)),
                        'token': post_token.make_token(user),
                        })
                else:
                    message = render_to_string('blog/post_request_email.html', {
                        'user': request.user,
                        'domain': current_site.domain,
                        'title': post.title,
                        'subtitle': post.subtitle,
                        'text': post.text,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'pid': urlsafe_base64_encode(force_bytes(post.pk)),
                        'token': post_token.make_token(user),
                        })
                user.email_user(subject, message)
                return redirect('post_detail', pk=post.pk)
        
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})




def post_confirm(request, uidb64, pidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        pid = force_text(urlsafe_base64_decode(pidb64))
        user = User.objects.get(pk=uid)
        post=Post.objects.get(pk=pid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and post_token.check_token(user, token):
        post.published_date = timezone.now()
        post.approval = user.first_name + " " + user.last_name
        post.approved = True
        post.save()
        return redirect('/')
    else:
        return render(request, 'blog/account_activation_invalid.html')

@login_required(login_url='/login/')
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    old_img = post.img
    if (request.method == "POST" and post.gruppo == request.user.profile.gruppo and request.user.is_staff or request.user.is_superuser and request.method == "POST"):
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            a_post = form.save(commit=False)
            a_post.author = request.user
            a_post.nomeautore = request.user.first_name + ' ' + request.user.last_name
            a_post.published_date = timezone.now()
            a_post.save()
            try:
                x = form.cleaned_data.get('x')
                y = form.cleaned_data.get('y')
                w = form.cleaned_data.get('width')
                h = form.cleaned_data.get('height')
            except (TypeError, ValueError, OverflowError):
                x = None
            if x is not None:
                form.save_img()  
                old_img.delete(False)          
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})

@login_required(login_url='/login/')
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if (post.gruppo == request.user.profile.gruppo and request.user.is_staff or request.user.is_superuser):
        post.img.delete(False) 
        post.delete(False)          
        return redirect('/')
    else:
        form = PostForm(instance=post)
        return render(request, 'blog/account_activation_invalid.html')



"""
LOGIN-SIGNUP ENVIRONMENT

"""



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.gruppo = form.cleaned_data.get('gruppo')
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            message = render_to_string('blog/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
        return HttpResponse("error")
    return render(request, 'blog/signup.html', {'form': form})
def account_activation_sent(request):
    return render(request, 'blog/account_activation_sent.html')
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.registration_date = timezone.now()
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        return redirect('/')
    else:
        return render(request, 'blog/account_activation_invalid.html')
def profile_detail(request):
    user = get_object_or_404(User, username=request.user)
    return render(request, 'blog/profile_detail.html', {'user': user})

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Esiste già un utente con questo username.'
    else:
        data['error_message'] = 'Questo va bene.'
    return JsonResponse(data)

def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(author=user).order_by('-published_date')
    context = {'posts': posts, 'user': user}
    return render(request, 'blog/user_detail.html', {'context': context})

"""
INSCRIPTIONS ENVIRONMENT

"""


@login_required(login_url='/login/')
def inscr_new(request):
    if request.method == "POST":
        form = InscrForm(request.POST)
        if form.is_valid():
            inscr = form.save(commit=False)
            inscr.author = request.user
            inscr.published_date = datetime.datetime.now()
            inscr.save()
            return redirect('inscr_detail', pk=inscr.pk)
    else:
        form = InscrForm()
    return render(request, 'blog/inscr_edit.html', {'form': form})
def inscr_detail(request, pk):
    inscr = get_object_or_404(Inscription, pk=pk)
    if (request.user.is_staff and request.user.profile.gruppo == inscr.first_choice or inscr.author == request.user or request.user.is_staff):

blog/templates/blog/account_activation_email.html
{% autoescape off %}
Ciao {{ user.username }},
benvenuto nel portale che riunisce tutti i gruppi scout AGESCI della zona di pistoia!

Questo è il tuo link per attivare l'account:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

blog/templates/blog/account_activation_invalid.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container verticalnonhero">
    <div class="well">
		<h2>Attivazione</h2>
		<p>Qualcosa e` andato storto, riprova!</p>
     </div>
</div>
{% endblock %}

blog/templates/blog/account_activation_sent.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container verticalnonhero">
    <div class="well">
    	  <h2>Attivazione</h2>
			<p>Email di attivazione inviata</p>
			<p>Controlla la tua mail per terminare il processo di registrazione!</p>
    </div>
</div>
{% endblock %}

blog/templates/blog/inscr_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<!--  App Features Section  -->
<div class="container verticalnonhero" style="margin-top: 20px;">
   <div class="place weel">
      {% if inscr.published_date %}
      <div class="date">
         {{ inscr.published_date }}
      </div>
      {% endif %}
      <h1>{{ inscr.fn_child }} {{ inscr.sn_child }}</h1>
      <p>Nome Genitore = {{ inscr.fn_parent }} {{ inscr.sn_parent }}</p>
      <p>Nome Figlio = {{ inscr.fn_child }} {{ inscr.sn_child }}</p>
      <p>Data di nascita = {{ inscr.dob_child }}</p>
      <p>Motivazione = {{ inscr.bio_child }}</p>
      <p>Prima scelta = {{ inscr.first_choice }}</p>
      <p>Seconda scelta = {{ inscr.second_choice }}</p>
      {% if inscr.author %}
      <div class="date">
         {{ inscr.author }}
      </div>
      {% endif %}
   </div>
</div>
<!--  And App Features Section  -->
{% endblock %}

blog/templates/blog/inscr_edit.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}
<div class="container verticalnonhero">
<form method="POST">
   {% csrf_token %}
   <div class="well">
      <h4 style="margin-top: 0">Nuova iscrizione</h4>
      <div class="flex-row row">
         <div class="form-group col-xs-6 col-sm-4 col-lg-3">
            <input required placeholder="Nome Genitore" class="form-control" id="id_fn_parent" maxlength="200" name="fn_parent" type="text" />
         </div>
         <div class="form-group col-xs-6 col-sm-4 col-lg-3">
            <input required placeholder="Cognome Genitore" class="form-control" id="id_sn_parent" maxlength="200" name="sn_parent" type="text" />
         </div>
         <div class="form-group col-xs-6 col-sm-4 col-lg-3">
            <input required placeholder="Nome Figlio" class="form-control" id="id_fn_child" maxlength="200" name="fn_child" type="text" />
         </div>
         <div class="form-group col-xs-6 col-sm-4 col-lg-3">
            <input required placeholder="Cognome Figlio" class="form-control" id="id_sn_child" maxlength="200" name="sn_child" type="text" />
         </div>
      </div>
      <div class="flex-row row">
         <div class="form-group col-xs-8 col-sm-8 col-lg-4">
            <p>Data di nascita:</p>
            <div class="flex-row row">
               <div class="col-xs-5 col-sm-5 col-lg-5">
                  <select display="inline-block" id="id_dob_child_month" name="dob_child_month" style="width: 100%; min-width: 125px; margin-right: 0px;">
                     <option value="1">Gennaio</option>
                     <option value="2">Febbraio</option>
                     <option value="3">Marzo</option>
                     <option value="4">Aprile</option>
                     <option value="5">Maggio</option>
                     <option value="6">Giugno</option>
                     <option value="7">Luglio</option>
                     <option value="8">Agosto</option>
                     <option value="9">Settembre</option>
                     <option value="10">Ottobre</option>
                     <option value="11">Novembre</option>
                     <option value="12">Dicembre</option>
                  </select>
               </div>
               <div class="col-xs-3 col-sm-3 col-lg-3">
                  <select display="inline-block" id="id_dob_child_day" name="dob_child_day" style="width: 100%; min-width: 70px; margin-right: 0px;">
                     <option value="1">1</option>
                     <option value="2">2</option>
                     <option value="3">3</option>
                     <option value="4">4</option>
                     <option value="5">5</option>
                     <option value="6">6</option>
                     <option value="7">7</option>
                     <option value="8">8</option>
                     <option value="9">9</option>
                     <option value="10">10</option>
                     <option value="11">11</option>
                     <option value="12">12</option>
                     <option value="13">13</option>
                     <option value="14">14</option>
                     <option value="15">15</option>
                     <option value="16">16</option>
                     <option value="17">17</option>
                     <option value="18">18</option>
                     <option value="19">19</option>
                     <option value="20">20</option>
                     <option value="21">21</option>
                     <option value="22">22</option>
                     <option value="23">23</option>
                     <option value="24">24</option>
                     <option value="25">25</option>
                     <option value="26">26</option>
                     <option value="27">27</option>
                     <option value="28">28</option>
                     <option value="29">29</option>
                     <option value="30">30</option>
                     <option value="31">31</option>
                  </select>
               </div>
               <div class="col-xs-4 col-sm-4 col-lg-4">
                  <select display="inline-block" id="id_dob_child_year" name="dob_child_year" style="width: 100%; min-width: 100px;">
                     <option value="2000">2000</option>
                     <option value="2001">2001</option>
                     <option value="2002">2002</option>
                     <option value="2003">2003</option>
                     <option value="2004">2004</option>
                     <option value="2005">2005</option>
                     <option value="2006">2006</option>
                     <option value="2007">2007</option>
                     <option value="2008">2008</option>
                     <option value="2009">2009</option>
                     <option value="2010">2010</option>
                     <option value="2011">2011</option>
                     <option value="2012">2012</option>
                  </select>
               </div>
            </div>
         </div>
         <div class="form-group col-xs-5 col-sm-4 col-lg-3">
            <p>Recapito telefonico:</p>
            <input required class="form-control" id="id_phone_parent" name="phone_parent" type="tel" pattern="\+?1?\d{9,15}$" />
            <p style="font-size: 12px;">Inserisci il prefisso nazionale prima del numero, per l'italia +39</p>
         </div>
      </div>
      <div class="flex-row row">
         <div class="form-group col-xs-12 col-sm-12 col-md-12">
            <textarea placeholder="Motivazioni" class="form-control" cols="40" id="id_bio_child" name="bio_child" rows="10"></textarea>
         </div>
      </div>
      <div class="flex-row row">
         <div class="form-group col-xs-6 col-sm-4 col-lg-3">
            <p>Prima scelta:</p>
            <select required class="form-control" id="id_first_choice" name="first_choice">
               <option value="">Nessuno</option>
               <option value="PT1">Pistoia 1</option>
               <option value="PT2">Pistoia 2</option>
               <option value="PT3">Pistoia 3</option>
               <option value="PT4">Pistoia 4</option>
               <option value="SG1">San Giorgio 1</option>
               <option value="QU1">Quarrata 1</option>
               <option value="MC1">Massa e Cozzile 1</option>
               <option value="CU1">Chiesina Uzzanese 1</option>
               <option value="UZ 1">Uzzano 1</option>
            </select>
         </div>
         <div class="form-group col-xs-6 col-sm-4 col-lg-3" style="margin-bottom: 50px;">
            <p>Seconda scelta:</p>
            <select required class="form-control" id="id_second_choice" name="second_choice">
               <option value="">Nessuno</option>
               <option value="PT1">Pistoia 1</option>
               <option value="PT2">Pistoia 2</option>
               <option value="PT3">Pistoia 3</option>
               <option value="PT4">Pistoia 4</option>
               <option value="SG1">San Giorgio 1</option>
               <option value="QU1">Quarrata 1</option>
               <option value="MC1">Massa e Cozzile 1</option>
               <option value="CU1">Chiesina Uzzanese 1</option>
               <option value="UZ 1">Uzzano 1</option>
            </select>
         </div>
      </div>
      <button type="button" class="inscr btn btn-default pull-right" style="margin-top: -30px;"><span class="glyphicon glyphicon-ok">  Conferma</span></button>
   </div>
<div class="modal fade" id="modalInscr">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">Stai per inserire una nuova iscrizione!</h4>
         </div>
         <div class="modal-body">
            <p> Congratulazioni! Stai per iscrivere tuo figlio nelle liste Scout Agesci della zona di Pistoia! Una volta cliccato su continua l'iscrizione sara' registrata e non sara' piu` possibile modificarla, ti preghiamo quindi di ricontrollare tutti i dati prima di procedere!</p>
         </div>
         <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
               <button type="button" data-dismiss="modal" class="btn btn-default ">Indietro</button>
            </div>
            <button type="save" class="btn btn-default" style="background: #ff807a;">CONTINUA</button>
         </div>
      </div>
   </div>
</div>
</form>
</div>
{% endblock %}
{% block javascript %}
<script src="{% static 'js/intlTelInput.js' %}"></script>
<script>
   $("#id_phone_parent").intlTelInput({
     // allowDropdown: false,
     // autoHideDialCode: false,
     // autoPlaceholder: "off",
     // dropdownContainer: "body",
     // excludeCountries: ["us"],
     // formatOnDisplay: false,
     // geoIpLookup: function(callback) {
     //   $.get("http://ipinfo.io", function() {}, "jsonp").always(function(resp) {
     //     var countryCode = (resp && resp.country) ? resp.country : "";
     //     callback(countryCode);
     //   });
     // },
     // hiddenInput: "full_number",
     initialCountry: "it",
     nationalMode: false,
     // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
     // placeholderNumberType: "MOBILE",
     // preferredCountries: ['cn', 'jp'],
     // separateDialCode: true,
     utilsScript: "{% static 'js/utils.js' %}"
   });
   $("#demo").intlTelInput("loadUtils", "lib/libphonenumber/build/utils.js");
</script>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

      <div class="container verticalnonhero">
         <h1>Login Richiesto</h1>
         <p> Per poter accedere a questa pagina occorre effettuare il login!</p>
         <p> Se ancora non sei registrato, che aspetti a farlo?! Clicca sul pulsante Registrati e accedi a tutte le funzioni del sito!</p>
         <form method="post">
            <div class="well">
               {% csrf_token %}
               {{ form.as_p }}
               <div style="margin-bottom: 40px;"><button type="submit" class="btn btn-default pull-left"><span class="glyphicon glyphicon-log-in"></span> Login </button>
               <button type="button" class="btn btn-default signup pull-right" > <span class="glyphicon glyphicon-registration-mark"></span> Registrati </button></div>
            </div>
         </form>
      </div>

{% endblock %}

blog/templates/blog/place_detail.html
{% extends 'blog/base.html' %}
{% block extra_head_content  %}

{% endblock  %}
{% block content %}
{% load l10n %}
<div class="container verticalnonhero">
   <div class="weel place">
      {% if place.published_date %}
      <div class="date">
         {{ place.published_date }}
      </div>
      {% endif %}
      <h1>{{ place.where }}</h1>
      <p>Tipo = {{ place.typ }}</p>
      <p>Riscaldamento = {{ place.heat }}</p>
      <p>Capienza = {{ place.capacity }}</p>
      <p>Costi = {{ place.cost }}</p>
      <p>Ultimo gruppo che ha visitato il posto  = {{ place.last_group }}</p>
      <p>Contatti  = {{ place.contacts }}</p>
      <p>Descrizione  = {{ place.description }}</p>
      <div id="map"></div>
      <script>
         function initMap() {
             var place = {lat: {{ place.coordinates.y|unlocalize }}, lng: {{ place.coordinates.x|unlocalize }}};
             var map = new google.maps.Map(document.getElementById('map'), {
                 zoom: 12,
                 center: place
             });
             var marker = new google.maps.Marker({
                 position: place,
                 map: map
             });
         }
      </script>
      <script async defer
         src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRU4ZZiIBGj2wkuA-tl6jEl4_i-ndD7DI&callback=initMap"></script>
      <p>Coordinate = <a href="https://www.google.com/maps/?q={{ place.coordinates.y|unlocalize }},{{ place.coordinates.x|unlocalize }}">  {{ place.coordinates.y|unlocalize }} {{ place.coordinates.x|unlocalize }} </a>
         {% if place.author %}
      <div class="date">
         {{ place.author }}
      </div>
      {% endif %}
   </div>
</div>
<!--  And App Features Section  -->
{% endblock %}